### ISSUE TITLE
Better error when table missing (with rom-sql)

### ISSUE THREAD

**Issue by robinetmiller** [rom-rb/rom-repository#10]
ROM dies with this misdirecting error:

`:users doesn't exist in ROM::RelationRegistry registry (ROM::Registry::ElementNotFoundError)`

When the `users` table hasn't yet been created in the database, but the relation is declared in Repository. If a plain relation is declared (ie. not using Repo) then rom-sql will raise a sensible table-not-there type error. 

Example: 

``` ruby
require 'rom-sql'
require 'rom-repository'

sql_uri = "mysql2://#{db_user}:#{db_password}@#{db_host}/#{db_database}"

rom_env = ROM.setup(default: [:sql, sql_uri]) do

    class MyRepository < ROM::Repository::Base
          relations :users
    end
end
```

**Comment by solnic** [comment]
This is no longer applicable since configuration has been separated from container
