### ISSUE TITLE
Using custom mappers with commands

### ISSUE THREAD

**Issue by flash-gordon** [rom-rb/rom-repository#21]
I know that the question was already asked in the chat by I want to keep a separate discussion here.
I really like how auto-generated mapper works and it suits me fine in most of cases. But I have a couple of exceptions as well. I want to wrap some keys from DB result into a nested hash before a model initialization. E.g. I want to group currency and amount into a money object.
I see two possible solutions: an ability to pass a custom mapper to a command that somehow replaces usage of MapperBuilder or an ability to pipe structs throw another mapper.

What do you about the case and possible solutions?

**Comment by flash-gordon** [comment]
I think that the first approach is better because it is also consistent with using a custom mapper while fetching data (RelationProxy#map_with).

**Comment by flash-gordon** [comment]
See #22.

**Comment by AMHOL** [comment]
Please see https://github.com/rom-rb/rom-repository/commit/ca659158ad11dce571faf149f486c07788d3ab8f

**Comment by flash-gordon** [comment]
So I guess it it resolved now I just forgot to add `closes` clause to the commit log.
