### ISSUE TITLE
Use existing registered commands when defining commands on repo

### ISSUE THREAD

**Issue by timriley** [rom-rb/rom-repository#29]
In [berg](http://github.com/icelab/berg) we have a custom [create_post command](https://github.com/icelab/berg/blob/master/lib/persistence/commands/create_post.rb), which does some stuff in `#execute` that we need.

It looks like when we declare and call a [:create command](https://github.com/icelab/berg/blob/master/apps/admin/lib/admin/persistence/repositories/posts.rb#L9) in the repo, this existing "create post" command is not actually used. It generates a whole new command object apart from the one that already exists.

Should repo just re-use any matching commands in cases like this?

**Comment by flash-gordon** [comment]
I'm not sure about dis. From my pov it's better to provide a DSL for setting existing command class, it'll be more explicit. If you use this one time then it shouldn't be verbose or boilerplate and if you do it many times then probably you should use plugins instead. Does it make sense?

/cc @solnic

**Comment by solnic** [comment]
yeah this should be solved via a custom plugin that extends `execute` and we should probably think about a better interface for plugins so that you don't have to override `execute`. Generated commands in repo are pre-configured, so we shouldn't just assume that a custom command will be properly configured too.

**Comment by solnic** [comment]
I tweaked `Repository#command` a couple of weeks back so that it does resolve existing commands and return them. Could you check if that works for you and your custom commands?

**Comment by timriley** [comment]
Can confirm this is working!

Existing custom command classes we now return via methods in repos like this:

``` ruby
def create(attrs)
  command(:posts)[:create].(attrs)
end
```
