### ISSUE TITLE
Require timing issue makes my mapper break

### ISSUE THREAD

**Issue by replaid** [rom-rb/rom-repository#3]
A somewhat different ordering issue than #2. 

Reproduction/reduction: https://gist.github.com/replaid/1a0a2a88147db0b949b4 The `rom-repository` require happens late because this file inlines a bunch of required files through the codebase this reproduction was created from. The file defining the `ROM::Repository::Base` subclass is the only file that needed `rom-repository`, so it was the one that required it. Apparently `rom-repository` wants to have been around for the registration of a mapper I use on results I get back from it.

Move the `require 'rom-repository'` up to just after the `rom-sql` require and this `KeyError` stops.

**Comment by replaid** [comment]
The error that gets raised (line number in repro.rb won't match the gist):

```
 ruby repro.rb
/Users/rep/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-repository-0.1.0/lib/rom/plugins/relation/view.rb:29:in `fetch': key not found: :base (KeyError)
    from /Users/rep/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-repository-0.1.0/lib/rom/plugins/relation/view.rb:29:in `attributes'
    from /Users/rep/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-repository-0.1.0/lib/rom/repository/loading_proxy.rb:160:in `method_missing'
    from /Users/rep/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-repository-0.1.0/lib/rom/repository/loading_proxy.rb:58:in `to_ast'
    from /Users/rep/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-repository-0.1.0/lib/rom/repository/loading_proxy.rb:79:in `mapper'
    from /Users/rep/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rom-repository-0.1.0/lib/rom/repository/loading_proxy.rb:47:in `map_with'
    from repro.rb:115:in `<main>'
```

**Comment by solnic** [comment]
This shouldn't be a problem anymore as plugins have been ported to rom and rom-sql enables them by default
