### ISSUE TITLE
Return tuple as a hash not struct

### ISSUE THREAD

**Issue by gotar** [rom-rb/rom-repository#31]
There should be an option in repository to globally turn off mapping tuples from relation to structs. In some cases, like basic json API we don't need objects at all. Using simple `to_json` we can convert `hash` or `array of hashes` to json directly.

Another problem, when you aggregate few relations, for exmaple:

```
module Persistence
  module Repo
    class Posts < Base[:posts]
      relations :posts, :comments
      commands :create, update: :by_id, delete: :by_id

      def [](id)
        aggregate(:comments).
          by_id(id).
          one!
      end
```

and even if you call `to_hash` on parent relation, children are still `Struct` it's normal behavior but complicate code a lot to just have raw tuples everywhere.

**Comment by solnic** [comment]
We should support this, but I'm not sure how. First, I need to clean up the code a bit before adding this functionality. I'm gonna do it in 0.4.0 though, too late for this now :(

**Comment by gotar** [comment]
I try to do it, but you are right. Right now struct are so connected with code it was hard.

**Comment by wojtekmaciej** [comment]
Maybe the better way is _deeply_to_hash_ method like this:
```ruby    
def deeply_to_hash(struct)
  struct.to_h.transform_values do |obj|
    if obj.is_a?(Array)
      obj.map { |a| deeply_to_hash(a) }
    elsif obj.class.superclass == ROM::Struct
      deeply_to_hash(obj)
    else
      obj
    end
  end
end
```

**Comment by wmaciejak** [comment]
Maybe the better way is deeply_to_hash method like this:

``` ruby
def deeply_to_hash(struct)
  struct.to_h.transform_values do |obj|
    if obj.is_a?(Array)
      obj.map { |a| deeply_to_hash(a) }
    elsif obj.class.superclass == ROM::Struct
      deeply_to_hash(obj)
    else
      obj
    end
  end
end
```

@gotar @solnic

**Comment by solnic** [comment]
I think the original issues was that we create intermediate representation (structs) just to get hashes back, while we have these hashes in the first place. So we just want to have a way of configuring repo (or requesting it at run-time) to skip struct mapping and return plain hashes.

**Comment by gotar** [comment]
Yeah it was about turning off (or provide some configuration option (etc)) to not changing tuple to struct automatically. Sometimes having hash is just enough

**Comment by solnic** [comment]
I didn't manage to deal with this in 1.0.0. Setting it up for 1.1.0.

**Comment by Kukunin** [comment]
What's the purpose of having structs? 

one more reason against structs:

```ruby
repo.container.relations[:users].first
=> {:id=>1, :address_id=>1}
repo.container.relations[:users].last
=> {:id=>2, :address_id=>2}
repo.users.first
=> #<ROM::Struct[User] id=1 address_id=1>
repo.users.last
=> {:id=>2, :address_id=>2}
```

Repository uses `RelationProxy` inside, and they act like decorator around original relations (I believe so). But returning structs instead of hashes (as original relations do) is violation of Liskov substitution principle

**Comment by flash-gordon** [comment]
@Kukunin as described in [this file](https://github.com/rom-rb/rom-repository/blob/b76229946896bc32d231bcbf81bb761a77430827/lib/rom/struct.rb) a struct class carries information about data types. Structs will raise an error on attempt to fetch a missing field, which is a good idea in most cases.

**Comment by Kukunin** [comment]
So, on one hand, struct behaves like a hash - no Liskov violation
on another hand, @gotar can't do `struct.to_json` (that's a root cause of this issue).

I've just tried `#to_json` on ROM::Struct, and it works fine. 
So, if we can support behaviour as hash has, we can live without globally turn off option, IMHO.

At least I've found there is no `#keys` method on ROM::Struct

**Comment by flash-gordon** [comment]
As for me `.to_json` shouldn't even exist. 
re `keys` and that's because structs aren't hashes. They do implement a subset of `Hash`'s interface, but that's it. TBH I can't get the idea of the full substitution here.

**Comment by gotar** [comment]
It's very old issue, originally created because I wrote any easy API (json) in roda. Where using plugin :`json` roda automatically convert every hash  or array or any other class you specify to json. 

So in ROM I was only returning tuple from db and automatically have JSON API, but with repository it's not possible. Because there was no possibility to just have raw tuple, it always create struct for me. 

No reason to go from hash to object to hash to json, when I can go from hash to json

**Comment by flash-gordon** [comment]
Yes, I get it, ofc not having a struct is a valid case :)

**Comment by solnic** [comment]
We can map to plain hashes, it is a feature I'd like to support

**Comment by solnic** [comment]
@Kukunin please don't use `first` and `last`, we have `one` and `one!` methods for retrieving a single object from a relation. We can't make `first` and `last` work efficiently with the mapping pipeline because their implementation can vary across adapters. I actually wish we didn't have `first` and `last` and it's something to deal with in rom 4.0

**Comment by Kukunin** [comment]
One more fact against structs in relation: mappers expect that relation returns an array of hashes, but combined relations return an array of structs, which causes mappers to fail.

That makes me think, that there is a good reason for `L` letter in SOLID principles.
