### ISSUE TITLE
Use associations from a schema of a root relation to set up repo's relations

### ISSUE THREAD

**Issue by flash-gordon** [rom-rb/rom-repository#35]
This way we won't need to provide them manually. Shouldn't be a problem, the only thing depending on this list is repo's constructor. 
@solnic we can even remove the manual configuration completely, wdyt?

**Comment by solnic** [comment]
Manual config of what?

**Comment by flash-gordon** [comment]
manual config of relations :) [this](https://github.com/rom-rb/rom-repository/blob/master/lib/rom/repository/class_interface.rb#L39-L53) class-level method

**Comment by solnic** [comment]
Doooh right :)

**Comment by solnic** [comment]
So, if we wanted to do this, we'd need to add a common interface to `Schema` for providing a list of all relations that a particular schema points to (ie via FKs, associations etc.). This should work for all adapters since rom-repo isn't sql-specific...

**Comment by flash-gordon** [comment]
You're right, but we can omit relations which was returned by the schema. This way we don't need to set relations in most of the cases, though that class-level setter will still be there.

**Comment by solnic** [comment]
> we can omit relations which was returned by the schema

WDYM? :)

**Comment by flash-gordon** [comment]
I meant those relations which was referenced by associations

**Comment by solnic** [comment]
@flash-gordon we could move `Relation#associations` and `AssociationSet` to core actually, as a plugin, then various adapters can enable it and things will Just Work™.  We actually need this anyway in order to make `combine` work (it currently assumes `associations` is available)

**Comment by flash-gordon** [comment]
yeah, sounds like a plan :)

**Comment by solnic** [comment]
@flash-gordon just ported associations core APIs from rom-sql to rom :)

**Comment by solnic** [comment]
So this is now totally possible, but it's too late to make this go into 1.0.0. We can add that in 1.1.0. I suspect it's gonna be something like this:

``` ruby
relations *root.schema.select(&:foreign_key?).map(&:target)
```

:)

**Comment by solnic** [comment]
I'll close this for now, it's very likely repos won't have to reconfigure relations at all, so they will simply accept a rom container and just use it as it is.

**Comment by flash-gordon** [comment]
@solnic makes sense!
