### ISSUE TITLE
Further example of how combine elements

### ISSUE THREAD

**Issue by mauricioklein** [rom-rb/rom-repository#39]
Hello!

I'm using the combine page documentation [here](http://www.rubydoc.info/github/rom-rb/rom-repository/master/ROM/Repository/RelationProxy/Combine) to build this relation, but not having success.

Would appreciate some help.

I've 2 data table: `User` and `Friend`.
`User` is referred by its ID.
`Friend` is a table with 3 attributes: `id`, `source_id` and `target_id`, where `source_id` and `target_id` are FK for `User`.

I want to get all friend for a user, so my initial version is:

> PS: `friend` and `user`, referred below, are Rom relations

``` ruby
User
  .where(id: user_id)
  .combine(
    many: { friends: [friend, id: :source_id] }
  )
  .one
```

This is working but, instead returning the friends model, it's returning only their IDs.

I want to return all the friend models, without their respective friends.

I've tried something like this:

``` ruby
User
  .where(id: user_id)
  .combine(
    many: { 
      friends: [friend.combine_parents(
        many: user
      ), id: :source_id] 
    }
  )
  .one
```

But nothing is being returned.

Would appreciate some help and, mainly, explanation about this logic, since it's not very clear in the documentation.
Once this part well understood, I'll be happy to improve the official documentation and submit a PR.

Thanks in advance for any help!

**Comment by mauricioklein** [comment]
Any update about this please?

**Comment by solnic** [comment]
Could you provide a standalone script with your table/relation/repo setup? It'd be easier for me to see how this could be done then.

**Comment by mauricioklein** [comment]
Thanks for your answer!

[Here](https://gist.github.com/mauricioklein/be5eaa6065823537070257ae8826b1e9)'s a git with sample entitites and relations.

In the friend entity, the _source_id_ is the one who requested the friendship, and _target_id_ is the one who accepted.

Basically, what I need is to fetch user information and all his friends.

So, supposing I'm fetching the information for user id = 1, and this user is friend with ids 2 and 3.

Basically, all the friends for user 1 will be those who are in the friend table as target and have the source_id = 1.

Data example:

User:

| id | name |
| --- | --- |
| 1 | User 1 |
| 2 | User 2 |
| 3 | User 3 |

Friend:

| id | source_id | target_id |
| --- | --- | --- |
| 1 | 1 | 2 |
| 2 | 1 | 3 |

So, I wanna return a structure like the following:

``` json
{
  "id": 1,
  "name": "User 1",
  "friends": [
    { "id": 2, "name": "User 2" },
    { "id": 3, "name": "User 3" } 
  ]
}
```

If you need any further information, feel free to ask.

Thanks in advance for the support so far!

**Comment by solnic** [comment]
hey, sorry for this late reply...I couldn't get this to work using association DSL, but here's what you could do using a custom view:

``` ruby
require 'rom-repository'
require 'rom-sql'
require 'logger'

class Users < ROM::Relation[:sql]
end

class Friends < ROM::Relation[:sql]
  view(:for_users, [:user_id, :id, :name]) do |users|
    select(:friends__source_id___user_id, :users__id, :users__name)
      .inner_join(:users, users__id: :friends__target_id)
      .where(friends__source_id: users.pluck(:id))
  end
end

config = ROM::Configuration.new(:sql, 'sqlite::memory')

config.gateways[:default].use_logger(Logger.new($stdout))

config.gateways[:default].connection.create_table(:users) do
  primary_key :id
  column :name, String
end

config.gateways[:default].connection.create_table(:friends) do
  primary_key :id
  foreign_key :source_id, :users
  foreign_key :target_id, :users
end

config.register_relation(Users, Friends)

class UserRepo < ROM::Repository[:users]
  commands :create
  relations :friends

  def with_friends(user_id)
    users.where(users__id: user_id).combine_children(many: friends).one!
  end
end

user_repo = UserRepo.new(ROM.container(config))

jane = user_repo.create(name: 'Jane')
john = user_repo.create(name: 'John')

user_repo.container.relations[:friends].insert(source_id: jane.id, target_id: john.id)

user_repo.with_friends(jane.id)
# #<ROM::Struct[User] id=1 name="Jane" friends=[#<ROM::Struct[Friend] user_id=1 id=2 name="John">]>
```

Generated queries:

```
I, [2016-10-01T06:49:43.394479 #26331]  INFO -- : (0.000072s) SELECT `id`, `name` FROM `users` WHERE (`users`.`id` = 1) ORDER BY `users`.`id`
I, [2016-10-01T06:49:43.395077 #26331]  INFO -- : (0.000082s) SELECT `friends`.`source_id` AS 'user_id', `users`.`id`, `users`.`name` FROM `friends` INNER JOIN `users` ON (`users`.`id` = `friends`.`target_id`) WHERE (`friends`.`source_id` IN (1)) ORDER BY `friends`.`id`
```

I'm gonna close this one and report another issue about adding support for this type of use cases to schema/associations.
