### ISSUE TITLE
Wrong Changeset#result for singular objects

### ISSUE THREAD

**Issue by Kukunin** [rom-rb/rom-repository#54]
For my specific changeset I want to pass my domain entities directly to it, and its mapper knows how to domain entity convert to hash of attributes.

However it causes `result` to be `:many` in case of single domain entity. 
It's because this line https://github.com/rom-rb/rom-repository/blob/master/lib/rom/repository/changeset/stateful.rb#L200 checks for Hash, not Array. 

Fix is easy: `__data__.is_a?(Array) ? :many : :one`

**Comment by Kukunin** [comment]
It causes such exception:

```
      undefined method `map' for #<Shift::Domain::HOI::Quote:0x0000000e03d230>
Did you mean?  tap
/usr/local/bundle/gems/rom-repository-1.0.0/lib/rom/repository/changeset/stateful.rb:159:in `to_a'
/usr/local/bundle/gems/rom-sql-1.0.0/lib/rom/sql/commands/create.rb:64:in `flatten'
/usr/local/bundle/gems/rom-sql-1.0.0/lib/rom/sql/commands/create.rb:64:in `with_input_tuples'
/usr/local/bundle/gems/rom-sql-1.0.0/lib/rom/sql/commands/create.rb:25:in `execute'
/usr/local/bundle/gems/rom-3.0.0/lib/rom/command.rb:279:in `call'
/usr/local/bundle/gems/rom-sql-1.0.0/lib/rom/sql/commands/error_wrapper.rb:12:in `call'
/usr/local/bundle/gems/rom-repository-1.0.0/lib/rom/repository/changeset/stateful.rb:169:in `commit'
```

**Comment by solnic** [comment]
Don't use changesets with objects other than Hash or Array. I'll improve exception message

**Comment by Kukunin** [comment]
why? if it has neat mapping facilities

**Comment by solnic** [comment]
@Kukunin hmm, the intention was to use them with plain hashes or arrays with hashes...but if you find it useful to use with other objects, then I'm 100% OK with a PR that will fix it
