### ISSUE TITLE
Add ability to tweak aggregate nodes

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-repository#56]
The `#aggregate` method has a limitation that you don't control the node relations, they are simply created by associations. The only way to tweak them is using custom association views, which has a limitation that they can't rely on run-time arguments (they are pre-defined). So, for cases like "fetch user aggregate with tasks matching these tags" we need a new feature.

I *think* something like this could be achieved:

``` ruby
def tasks(tags)
  aggregate(:tasks).node(:tasks) { |tasks| tasks.with_tags(tag_name: tags) }
end
```

How does this look? Any other ideas? /cc @timriley @flash-gordon @AMHOL

**Comment by timriley** [comment]
I like it. It'd be nice to combine the ease of the `#aggregate` API while still being able to pass runtime data. I presume you'd see these `#node` calls being chain-able? How'd you think you'd be able to specify something for a more deeply nested node?

**Comment by solnic** [comment]
>  I presume you'd see these #node calls being chain-able?

Yep, chainable

>  How'd you think you'd be able to specify something for a more deeply nested node?

Through a nested hash:

``` ruby
aggregate(posts: [:authors, :tags]).node(posts: :authors) { |authors| authors.admins }
```

**Comment by flash-gordon** [comment]
@solnic views can have arguments, so something like `repo.aggregate(many: repo.tasks.by_title('Jane Task')).to_a` already works, right? OK, it works, I tested 😄 However, it's not going to work for deeply nested associations, so 👍

**Comment by solnic** [comment]
@flash-gordon yes this is needed for deeply nested graphs :)

**Comment by solnic** [comment]
Please take a look at #63 PR which adds this feature
