### ISSUE TITLE
Mappers for combined relations

### ISSUE THREAD

**Issue by Kukunin** [rom-rb/rom-repository#61]
It is useful to have an ability to map combined results from combined relations. Something like:

    customer.combine_parents(one: avatars).as(:entity).by_id(id)

Currently it doesn't work. Here is test reflecting the feature

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required.'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rom'
  gem 'rom-sql'
  gem 'rom-repository'
  gem 'sqlite3'
  gem 'rspec'
  gem 'pry'
end

require 'rspec/autorun'

class Address < Dry::Struct
  attribute :street_name, Dry::Types['strict.string']
  attribute :city, Dry::Types['strict.string']
end

class User < Dry::Struct
  attribute :address, Address.optional
end

class UsersMapper < ROM::Mapper
  relation :users
  register_as :entity

  attribute :address, &->(value) { value }

  model User

  # That's because combined relations returns array of structs
  def call(value)
    super(value.map(&:to_h))
  end
end

describe ROM::Repository do
  let(:rom) { ROM.container(configuration) }
  let(:configuration) do
    ROM::Configuration.new(:sql, 'sqlite::memory').tap do |config|
      config.default.create_table(:users) do
        primary_key :id
        foreign_key :address_id, :addresses, null: false
      end

      config.default.create_table(:addresses) do
        primary_key :id
        column :street_name, String, null: false
        column :city, String, null: false
      end
      config.register_mapper(UsersMapper)
    end
  end

  let(:repo) do
    Class.new(ROM::Repository[:users]) do
      relations :addresses
    end.new(rom)
  end

  before { create_user(street_name: 'street', city: 'city') }

  context 'with single relation' do
    let(:relation) { repo.users.as(:entity) }

    it { expect(relation.one).to be_a(User) }
    it { expect(relation.one.address).to be_nil }
  end

  # this one doesn't work
  context 'with naive combined relation' do
    let(:relation) { repo.users.combine_parents(one: repo.addresses).as(:entity) }

    it { expect(relation.one).to be_a(User) }
    it { expect(relation.one.address).not_to be_nil }
  end

  context 'with workarounded combined relation' do
    let(:mapper) { rom.mappers[:users][:entity] }
    let(:combined_relation) { repo.users.combine_parents(one: repo.addresses) }
    let(:relation) { ROM::Relation::Composite.new(combined_relation, mapper) }

    it { expect(relation.one).to be_a(User) }
    it { expect(relation.one.address).not_to be_nil }
  end

  def create_user(address)
    address_id = rom.relations[:addresses].insert(address)
    rom.relations[:users].insert(address_id: address_id)
  end
end
```

I've included workaround as well in test above. It requires a hack in Mapper as well, to map rom structs to hashes (hello https://github.com/rom-rb/rom-repository/issues/31)

Tell me what do you think

**Comment by Kukunin** [comment]
btw, inner mappers `repo.users.combine_parents(one: repo.addresses.as(:address_mapper))` don't work as well. Should I create a separate issue for it?

**Comment by Kukunin** [comment]
Do you think relation views can help somehow with mapping? both nested and composite relations

**Comment by solnic** [comment]
> btw, inner mappers repo.users.combine_parents(one: repo.addresses.as(:address_mapper)) don't work as well

What does it mean that they don't work? Any backtrace?

**Comment by solnic** [comment]
> Do you think relation views can help somehow with mapping? both nested and composite relations

Yes relations views can return mapped data depending on what your db supports. In this case though I don't think there's much you can achieve with them, except renaming columns. As I mentioned in gitter what I want to do is support for wrapping attributes in order to have them nested as an embedded value object, without the need to use external relation+join. It should not be hard to do, so expect to see this in next version of repo.

**Comment by Kukunin** [comment]
`repo.users.combine_parents(one: repo.addresses.as(:address_mapper)) ` doesn't map addresses. 
It works without any crash, but mapper isn't called. https://gist.github.com/Kukunin/86d4b15fe57dd61ef8d379a9f306f3cf

Wrapping and renaming are specific cases of some mappings. 
Maybe, instead of doing different things differently, we can focus on great mapping chain (assign mapper to sub-relation, combined relation etc) and then will build high level features based on them, with providing ability to do more with mappers.

As I understood, all manipulations goes in the memory, so there is a possibility to add mappers to the chain, but currently there is no good API for that

**Comment by solnic** [comment]
I guess once we have #56 in place we could make something like this work:

``` ruby
aggregate(:address).nodes(:address) { address.map_with(:my_mapper) }
```

**Comment by solnic** [comment]
One more thing, if a custom mapper was set on the root relation, then we need to disable mapping to structs on nodes too. This way you won't have to override call to dump structs to hashes and it'll be more consistent (since setting a custom mapper disables structs for the root already).

**Comment by solnic** [comment]
Can this be closed?

**Comment by Kukunin** [comment]
So, eventually this specific feature (mappers for combined relation) isn't implemented, and with this PR is closed, won't be. In current implementation, rom calls mapper with Graph relation before it combines results.

That seems be ok for me, because actually I can't find any good application for this: using already-mapped relations before combination seems enough.

I tried `#node` usage, which seems cool, but it has own caveats: 
* it can't return domain models, only hashes or something that behaves like hashes (rom structs)
* it can't rename column, otherwise internal schema will fail

So it doesn't work well with mapping. 

What works decently with mapping is relation `view`, which we have so little info about.

Eventually I've got my gist working here in 3rd revision https://gist.github.com/Kukunin/86d4b15fe57dd61ef8d379a9f306f3cf

```ruby
        view :as_entity do
          schema { rename(nname: :name) }
          relation { as(:entity) }
        end
```

I don't like that I need that view schema is coupled to the mapper (if I need to rename one more column, I need to update schema), but that's ok for now. Neither I understand why do we need to use schema for relation (coercing? validation? assertion?)

I still feel, that we have some kind of mess inside with mappers:
* I still can't do `users.map_with(:my_mapper).as(User)`
* There are different built-in mappers used in different placed - it doesn't look like a pipeline of mappers

I believe we can simplify this, but I that's probably a milestone for next big release, because it requires to break public API.

@solnic it's up to you to decide either to close this issue, or keep track on this. Currently, it seems I can implement what do I need via relation `views`. More information is coming when I'll be implementing it =)

**Comment by solnic** [comment]
Oh sorry, I didn't give you enough info. So with 1.1.0 you can do this:

``` ruby
repo.aggregate(:address).as(:entity, auto_map: true)
```

This will apply your mapper after auto-mapping, so you'll get final structure in your mapper which should be much easier to process.

**Comment by Kukunin** [comment]
ok. that works specifically for this issue =)
