### ISSUE TITLE
"something is wrong with constructor types"

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom-repository#62]
Custom read types is not respected in ROM-Repository.

https://gist.github.com/kwando/fac39e7a2c61bfb44873e4f1207ff663

@flash-gordon in rom-rb@gitter
"something is wrong with constructor types, apparently the serialization block is called on deserialized data in rom-repo, pls file an issue, we need to fix it"

**Comment by flash-gordon** [comment]
Ah, snap! We're using write types for [structs](https://github.com/rom-rb/rom-repository/blob/b76229946896bc32d231bcbf81bb761a77430827/lib/rom/repository/struct_builder.rb#L53) 🙈  I'll fix it and push a release right away!

**Comment by flash-gordon** [comment]
@kwando I released 1.0.2, and your example now works

@solnic I kind of fixed it but now I'm not sure about the changes I made. If we use read types from relations in struct this means a type constructor will be called twice (one time by output schema and one time by struct's schema), and thus it is required to ignore already coerced data. For instance, such a caveat will force us to change some of PG types we have in rom-sql. What do you think about this?
