### ISSUE TITLE
repo.changset with custom UpdateChangeset

### ISSUE THREAD

**Issue by kwando** [rom-rb/rom-repository#66]
Support using a custom UpdateChangsets in rom-repository.

I basically wanna do ```user_repo.changeset(user.id, params)``` but with my own ```UpdateUserChangeset``` class

**Comment by jasper-lyons** [comment]
Hey @kwando, it looks like you'd need to do:

[`repo.changeset(UpdateUserChangeset).data(id: user.id, **params)`](http://rom-rb.org/learn/repositories/custom-changesets/)

Does that achieve what you wanted?

**Comment by solnic** [comment]
That's not gonna work, the only way to restrict changet's relation by PK is to use `changeset(pk_value, new_data)` so this does require extending existing API. I don't have any idea how it should look like though. Maybe:

``` ruby
user_repo.changeset(user.id, params, UpdateUserChangeset)
```

?

**Comment by jasper-lyons** [comment]
Why not take the pk from the data?

**Comment by solnic** [comment]
@jasper-lyons because it's too implicit. you may have PKs like UUID and then we can't determine whether it's meant to be a new tuple or we want to update existing one

**Comment by jasper-lyons** [comment]
That makes sense. Does 'by_pk()' return an object you could call changesets on?

**Comment by solnic** [comment]
Yes. Structs are coercible to hashes so they work with changesets and commands

**Comment by jasper-lyons** [comment]
My immediate thoughts here were to do something like:

```ruby
user_repo.by_pk(user.id).changeset(params, UpdateUserChangeset)
```

But that is quite the detraction from the existing API.

**Comment by solnic** [comment]
@jasper-lyons I'm glad you mentioned this, if you take a look [at the rom 4.0 roadmap](https://discuss.rom-rb.org/t/rom-4-0-roadmap-draft/133) I posted earlier today, you'll see that it talks about moving changeset to core, or to rom-changeset. This would be a good opportunity to think about having `Relation#changeset` method, which is almost what you proposed. The difference is that repository methods are meant to return data, not relations, so this means we *could* have this:

``` ruby
users.by_pk(user.id).changeset(params, UpdateUserChangeset)
```

...however, this is stuff for rom 4.0, now we have changeset in repos only :)
