### ISSUE TITLE
Add Returning Domain Objects from CUD commands to documentation

### ISSUE THREAD

**Issue by jasper-lyons** [rom-rb/rom-repository#67]
I eventually figured out how to do this after stepping through the code execution but adding some documentation for others would be useful. Especially given the current lack of [documentation on mappers](http://rom-rb.org/learn/advanced/mappers/).

Informing developers on how to uniformly return domain objects from both commands and queries would have been useful for me.

Just a simple example + description like:

```ruby
module Types
  include Dry::Types.module
end

class Account < Dry::Struct
  attribute :id, Types::Int
  attribute :email, Types::String
end

class AccountsMapper < ROM::Mapper
  relation :accounts
  register_as :entity
  model Account
end

rom_config.register_mapper(AccountsMapper)

class AccountRepo < ROM::Repository[:accounts]
  commands :create, update: :by_pk, delete: :by_pk, mapper: :entity

  def query(conditions)
    accounts.where(conditions).as(Account)
  end
end
```

**Comment by solnic** [comment]
Closing this since things changed in rom 4.0 and it works consistently via setting struct namespace. Docs will be updated along with 4.0 final.
