### ISSUE TITLE
Allow Custom Commands on Repositories CUD Operations

### ISSUE THREAD

**Issue by jasper-lyons** [rom-rb/rom-repository#68]
Currently only the base CUD commands are available on repositories. Even if you define an register a custom command, it is not used due to the way commands are compiled via the `commands` macro.

This would be useful for adapters like the Redis adapter where creating, updating and deleting objects can be achieved in a variety of ways, all of which cannot be covered with some default commands.

Below I discuss how we might go about doing this.

```ruby
    config = ROM::Configuration.new(:memory)

    config.relation(:accounts) do
      register_as :accounts   

      # avoid pulling in plugin, use :key_inference
      def base_name
        name
      end
    end

    class CreateAccount < ROM::Commands::Create[:memory]
      relation :accounts
      register_as :create
      result :one

      def execute(tuple)
        byebug
      end
    end

    config.register_command(CreateAccount)

    rom = ROM.container(config)

    account_repo = Class.new(ROM::Repository[:accounts]) do
      commands :create
    end

    repo = account_repo.new(rom)

    repo.create({})
```

Currently, this will completely bypass the `CreateAccount` class and build and register a new `ROM::Memory::Commands::Create` command. This is because of this [if statement](https://github.com/rom-rb/rom-repository/blob/master/lib/rom/repository/command_compiler.rb#L117). Because [type](https://github.com/rom-rb/rom-repository/blob/master/lib/rom/repository/command_compiler.rb#L98) simply searches for `ROM::Commands::Create[<adapter here>]` and if it is a constant, builds and registers a command with it, we never get the opportunity to do [this](https://github.com/rom-rb/rom-repository/blob/master/lib/rom/repository/command_compiler.rb#L153):

```ruby
registry[name][id] = container.commands[name][id]
[name, id]
```

Here, instead of building and registering a new command we simply pass the existing custom command through. To support this we should change the priority of checks so that first we see if a command already exists in the `container.commands` registry.

e.g.

```ruby
if container.commands.key?(name) && container.commands[name][id]
```
If it exists we can register the command

```ruby
    registry[name][id] = container.commands[name][id]
```

else we can build a new command!

```ruby
elsif type
    # compile a default command
    register_command(name, type, meta, parent_relation)
```

On caveat, we need to register the default command with it's `default_name` instead of it's `type`.

```ruby
registry[rel_name][type.default_name] = klass.build(relation, input: relation.input_schema)
```

instead of [this](https://github.com/rom-rb/rom-repository/blob/master/lib/rom/repository/command_compiler.rb#L194)

```ruby
 registry[rel_name][type] = klass.build(relation, input: relation.input_schema)
```

Which stores the command against it's class / type name. Not doing this unifies the interface for accessing commands to symbols like `:create`, `:update`, `:delete` for all commands.

After that, we can continue to do all of the work discovering the mappings, [here](https://github.com/rom-rb/rom-repository/blob/master/lib/rom/repository/command_compiler.rb#L127)

Finally we simply do this

```ruby
if other.size > 0
    [mapping, [id, other]]
else
    [mapping, id]
end
```
which will work because now all commands are registered with id's like `:create`, `:update` etc.

**Comment by solnic** [comment]
Thanks for this thorough investigation. We already support custom commands but create, update, delete are treated separately and are always generated, as you discovered. I'm not against changing it so that if there's a command registered as create, update or delete then it'll be used. This will be less surprising.

**Comment by jasper-lyons** [comment]
I have a rough implementation and tests prepared, should I submit a pull request? I'd love some comments on how to better structure the test.

**Comment by solnic** [comment]
@jasper-lyons yes please

**Comment by johnnoone** [comment]
I'm interested about this improvement too.
Do you have any visibility about it's resolution?

**Comment by solnic** [comment]
@johnnoone I'll address this in rom 4.0. The PR from @jasper-lyons needs to be a bit reworked since now command compiler is detached from repositories and lives in rom-core

**Comment by jasper-lyons** [comment]
This is true! Will implement this afresh in 4.0 or would you prefer me to update the PR?

**Comment by solnic** [comment]
@jasper-lyons oh sweet! feel free to join our rom-4.0 party and open a PR in rom-rb/rom then :)

**Comment by solnic** [comment]
There's a chance this already works in rom master. I'm gonna close this issue, if any work is still needed, I'm looking forward to PRs in main rom repo on github.
