### ISSUE TITLE
Run-time authentication

### ISSUE THREAD

**Issue by pnomolos** [rom-rb/rom-repository#70]
My issue is specific to `rom-http`, but I can provide an analogue for `rom-sql`.  Suppose you have a backend database console webapp, where people log in using their actual DB credentials.  Rather than having a launch-time configuration for `ROM::Configuration` you're going to need to dynamically configure on the fly.

Now, I'm well aware that with a DB adapter you'd likely need a different physical connection created for each set of credentials, but with an HTTP (or other) transport, it's more likely that you're providing the authentication information with every request, so in terms of run-time objects you can re-use most of them.  I'd like to propose something such as:

```ruby
rom = ROM::Configuration.new(:http, global_configuration)
authenticated_rom = rom.auth(username: u, password: p, adapter_specific_secret_token: t)
```

I'd love to create a PR, but I'm just starting with `rom` so I'm not even sure where to get started!

**Comment by solnic** [comment]
I'm about to close issue tracker for this repo, so just FYI if you'd like to discuss this further please start a thread on discourse.rom-rb.org.
