### ISSUE TITLE
Command macro - specify entity to be mapped to

### ISSUE THREAD

**Issue by pnomolos** [rom-rb/rom-repository#71]
Right now you have to do things manually (see #67) to have commands map directly to domain objects.  It would be nice if you could specify what that domain object is directly from the command macro, something like this (code borrowed from #67):

```ruby
module Types
  include Dry::Types.module
end

class Account < Dry::Struct
  attribute :id, Types::Int
  attribute :email, Types::String
end

# We don't need this anymore
# class AccountsMapper < ROM::Mapper
#   relation :accounts
#   register_as :entity
#   model Account
# end

# rom_config.register_mapper(AccountsMapper)

class AccountRepo < ROM::Repository[:accounts]
  commands :create, update: :by_pk, delete: :by_pk, entity_class: Account
  # Alternatively, entity_class: 'Account' if the class doesn't exist when AccountRepo is loaded

  def query(conditions)
    accounts.where(conditions).as(Account)
  end
end
```

**Comment by solnic** [comment]
Is it expected that this setting will apply to all defined commands?

**Comment by flash-gordon** [comment]
@solnic we already have `mapper:` option in the macro, I was thinking about allowing to pass a class, not only a symbol, same as `Proxy#as` accepts either a symbol or a class.

**Comment by solnic** [comment]
@flash-gordon yes that's how it should be done, or even `commands :create, as: Account` maybe

**Comment by pnomolos** [comment]
@solnic I think it's a reasonable assumption that it's going to apply to all (`create` and `update` only, I suppose) commands?

**Comment by solnic** [comment]
@pnomolos why not to `delete` too? or any other command type

**Comment by pnomolos** [comment]
@solnic I made the assumption that delete doesn't return an entity ;)  I guess applying to any command makes sense - if you want to use a different entity (or the auto-generated one) then just call the macro multiple times for different commands?

**Comment by jasper-lyons** [comment]
For consistency, applying it to all commands leaves the users less confused.

Maybe break the macro down into multiple calls?

e.g.
```ruby
class AccountRepo < ROM::Repository[:accounts]
  command :create, as : Account
  command update: :by_pk, as: Account
  command delete: :by_pk, as: Account
  # commands :create, update: :by_pk, delete: :by_pk, entity_class: Account
  # Alternatively, entity_class: 'Account' if the class doesn't exist when AccountRepo is loaded

  def query(conditions)
    accounts.where(conditions).as(Account)
  end
end
```

**Comment by solnic** [comment]
Starting from rom 4.0 it's possible to define a custom struct namespace (either on relations or repositories), which pretty much provides this kind of functionality, so, I'm closing this.
