### ISSUE TITLE
Missleading error message if table name is "relations"

### ISSUE THREAD

**Issue by choallin** [rom-rb/rom-repository#72]
I have a table "relations" where I save the relations of customers (parent, sibling,...)
Since this name is the same name rom is using internally for a method every time I use this repo, it crashes with this error message:  

>NoMethodError: undefined method `as' for #<ROM::RelationRegistry:0x0055dc83a76c18>
>    /home/gergra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-3.0.1/lib/rom/registry.rb:47:in `block in method_missing'
>    /home/gergra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-3.0.1/lib/rom/registry.rb:47:in `fetch'
>    /home/gergra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-3.0.1/lib/rom/registry.rb:47:in `method_missing'
>    /home/gergra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hanami-model-1.0.0.beta1/lib/hanami/model/mapped_relation.rb:31:in `initialize'
>    (eval):3:in `new'
>    (eval):3:in `relations'
>    /home/gergra/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rom-repository-1.1.0/lib/rom/repository/root.rb:62:in `initialize'

It would be great, if you can handle every table name, or if this would be to complex, you could print a more meaningful error message.

@flash-gordon pointed to this line: https://github.com/rom-rb/rom-repository/blob/9dffbcc822c2dd96c89c92f0849cb9ae3406ddcf/lib/rom/repository/root.rb#L62

Which was changed in this commit:
https://github.com/rom-rb/rom-repository/commit/4acbd9ee1d3449017d21c4b4a25a1db97c2c067e/

**Comment by solnic** [comment]
Closing in favor of https://github.com/rom-rb/rom/issues/434
