### ISSUE TITLE
Module confuses sequel lookup

### ISSUE THREAD

**Issue by robinetmiller** [rom-rb/rom-repository#8]
Wrapping the Relation & Repository definitions in a module cause LoadingProxy to not use the defined Relation, instead using the auto-generated one. 

From Gitter: 

> @solnic: Unfortunatly sequel does not raise when you ask for a dataset that isn't a real table.

Here's my mini example, uncomment the `dataset` call to see the difference: 

``` ruby
require 'rom-sql'
require 'rom-repository'

module MyProject
  ROM.use :auto_registration

  ROM.setup(default: [:sql, "mysql2://#{'username'}:#{'password'}@#{'localhost'}/#{'dbname'}"])

  class Users < ROM::Relation[:sql]
    # required to make it happy
    # dataset :users

    view(:by_name, [:id, :name]) do |id|
      where(id: id).select(:id, :name)
    end
  end

  class DemoRepository < ROM::Repository::Base
    relations :users

    def users_by_name(name)
      users.by_name(name)
    end
  end

  rom_env = ROM.finalize.env

  persister = DemoRepository.new(rom_env)

  persister.users_by_name('Bob')
end
```

**Comment by solnic** [comment]
I'm gonna close this one and report another issue in rom-sql about disabling auto-inferring relations by default, this has been an issue in general that bites people all the time.
