### ISSUE TITLE
update changeset doesn't work when mapper renames the key

### ISSUE THREAD

**Issue by Kukunin** [rom-rb/rom-repository#89]
I separated my underlying SQL schema and provide domain interface to the rest of application. 

My entity has an `:file` attribute, which is associated entity. And an update changeset expects `:file` key which is mapped to internal `:file_id` column via changeset mappers (awesome thing, btw).

With `1.3.2` release it stopped to work, I've figured out because of this commit: https://github.com/rom-rb/rom-repository/commit/518a9d919e913eff4ac41db01d81b9441dc73825.

Because original tuple doesn't contain `:file` but `:file_id`, `:file` attribute gets filtered out of changeset without any warning.

I believe, since we have mapping facilities, and renaming keys are expected mapping (at least wrapping/unwrapping of value objects), this should be considered as bug.

**Comment by johnnoone** [comment]
same problem here. I had to decorate the `original` method to make it work as expected:

```ruby
class UpdateWithRename < ROM::Changeset::Update
  ...
  def original
    super.merge(my_virtual_field: nil)
  end
end
```

**Comment by solnic** [comment]
We're working on a fix for this in #90

**Comment by solnic** [comment]
@Kukunin could try with latest master?

**Comment by johnnoone** [comment]
latest release works fine for my case. thanks!
