### ISSUE TITLE
Repository constructor should complain when given an unfinalized env

### ISSUE THREAD

**Issue by robinetmiller** [rom-rb/rom-repository#9]
Since repository apparently expects a finalized env, it should complain if it doesn't get one. 

``` ruby
unfinished_env = ROM.setup(default: [:sql, "mysql2://#{'username'}:#{'password'}@#{'hostname'}/#{'dbname'}"])

class DemoRepository < ROM::Repository::Base
  relations :users
end

full_env = ROM.finalize.env

DemoRepository.new(unfinished_env) # should fail

DemoRepository.new(full_env) #should pass

```

**Comment by robinetmiller** [comment]
@endash has suggested refactoring the way setup and env exist and behave during the setup process. If that ends up happening, it may redefine/solve this issue.

Edit: His sketch proposal is here: https://gist.github.com/endash/3b436aa0d90fedc41c8b

**Comment by solnic** [comment]
This is an obsolete issue, closing
