### ISSUE TITLE
Can't use .select on RelationProxy via SimpleDelegator

### ISSUE THREAD

**Issue by flash-gordon** [rom-rb/rom-repository#91]
`RelationProxy` is a subclass of `Object` and has its own `#select` inherited from the `Kernel` module. For a reason which is unclear to me this code works
```ruby
repo.users.select.class # => ROM::Repository::RelationProxy
```
and this doesn't:
```ruby
Wrapper = Class.new(SimpleDelegator)
Wrapper.new(repo.users).select
# => ArgumentError: wrong number of arguments (given 0, expected 1..4)
# from /Users/gordon/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/delegate.rb:83:in `select'
```
Removing `#select` from `RelationProxy` fixes the issue however I still don't get why the first block works fine. @solnic do you know why?

`SimpleDelegator` [is used by Hanami](https://github.com/hanami/model/blob/e63f883152fc350eb202f21f29675e6052459d39/lib/hanami/model/mapped_relation.rb).

**Comment by solnic** [comment]
> For a reason which is unclear to me this code works
> repo.users.select.class # => ROM::Repository::RelationProxy

This is a mystery. We should undef `select` method to fix this.

Re SimpleDelegator, I didn't use it because I don't trust it. We need customized decoration anyway.

**Comment by flash-gordon** [comment]
@solnic that's because `Delegator` calls `__send__` and not `public_send`. Do we still need to remove `select` in `RelationProxy` or ask to change the behavior on the Hanami side?

**Comment by solnic** [comment]
@flash-gordon it seems to be a problem 100% on the rom side so we should deal with it somehow

**Comment by flash-gordon** [comment]
`¯\_(ツ)_/¯`
I've never thought about it, but Ruby invokes `method_missing` if you call a private method. `__send__`/`send` bypasses this mechanism and invokes the method directly.

**Comment by solnic** [comment]
Things you learn when you're building libraries eh? :)

**Comment by flash-gordon** [comment]
exactly!

**Comment by jodosha** [comment]
Hi folks, unfortunately this problem is still happening: https://github.com/hanami/model/issues/451#issuecomment-336381375

**Comment by flash-gordon** [comment]
@jodosha yeah, I had a look into this yesterday night, the problem is that hanami-model uses composite relations that in order delegates calls too, I don't have a fix yet but will get back with it

**Comment by solnic** [comment]
You need to `undef :select`

**Comment by jodosha** [comment]
@solnic Because we use `SimpleDelegator`, `undef :select` doesn't work:

```
NameError: undefined method `select' for class `Hanami::Model::MappedRelation'
```

---

In order to remove `SimpleDelegator` out the equation, I tried to declare a concrete method:

```ruby
      def select(*args, &blk)
        __getobj__.select(*args, &blk)
      end
```

But still getting:

```
     TypeError:
       no implicit conversion of Symbol into IO
```

Please note that `__getobj__` is a `ROM::Repository::RelationProxy`, which is wrapping a `ROM::Relation::Composite`.

---

Is it possible to have `ROM::Repository::RelationProxy#method_missing` to use `#public_send` instead of `#__send__`?

**Comment by solnic** [comment]
> Is it possible to have ROM::Repository::RelationProxy#method_missing to use #public_send instead of #__send__?

Yes

**Comment by flash-gordon** [comment]
@jodosha @solnic I fixed delegation of private methods in `core` and pushed `rom 3.3.2`, everything's ok now. For me it's a reasonable decision because I don't see a point in calling private methods on proxies

**Comment by jodosha** [comment]
@flash-gordon @solnic Thank you very much! That was our last blocker to release both `1.0.4` and `1.1.0.beta4`! 🎉  💚 💛 ❤️ 💙 .

Then I can get back to the inflector gem for dry-rb!
